# Generated by Django 3.2.8 on 2021-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='Email field', max_length=100),
        ),
    ]
