# Generated by Django 3.2.8 on 2021-10-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0003_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
        ),
    ]
